# Generated by Django 5.2.8 on 2025-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveIntegerField()),
                ('max_units', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
