# Generated by Django 5.2.8 on 2025-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
