# Generated by Django 5.2.8 on 2026-01-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_enrollmentsettings_is_active'),
        ('enrollment', '0004_alter_enrollmentsettings_is_active_enrollment'),
    ]

    operations = [
    ]
