# Generated by Django 5.2.8 on 2025-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='course.course')),
                ('sessions', models.ManyToManyField(related_name='courses', to='course.classsession')),
            ],
        ),
    ]
