# Generated by Django 5.2.8 on 2025-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='faculty',
            field=models.CharField(choices=[('eng', 'دانشکده فنی و مهندسی'), ('sci', 'دانشکده علوم'), ('lit', 'دانشکده ادبیات'), ('psy', 'دانشکده روان شناسی'), ('art', 'دانشکده هنر')], default='eng', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='day',
            field=models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یکشنبه'), ('mon', 'دوشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهارشنبه')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
