# Generated by Django 5.2.8 on 2025-12-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsession',
            options={'verbose_name': 'Class Session', 'verbose_name_plural': 'Class Sessions'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='unit',
            new_name='units',
        ),
    ]
