# Generated by Django 5.2.8 on 2025-12-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_classsession_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='faculty',
            field=models.CharField(choices=[('eng', 'مهندسی'), ('sci', 'علوم'), ('lit', 'ادبیات'), ('art', 'هنر')], default='eng', max_length=20),
        ),
    ]
